name: kidscare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.6
  http: ^1.4.0
  shared_preferences: ^2.5.3
  get: ^4.7.2
  dartz: ^0.10.1
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca-Thin.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/splash_logo.png
  android: true
  ios: true
  web: false
